title: SYNTAX
theme: just-the-docs

url: https://littleweirdo410.github.io/syntax_handbook

aux_links:
  "GitHub":
    - "//github.com/littleweirdo410/syntax_handbook"

aux_links_new_tab: true

heading_anchors: true

nav_enabled: true

kramdown:
  parse_block_html: true
