title: SYNTAX
theme: just-the-docs

plugins:
  - jekyll-toc

toc:
  ordered_list: true

url: https://littleweirdo410.github.io/syntax_handbook

aux_links:
  "GitHub":
    - "//github.com/littleweirdo410/syntax_handbook"

aux_links_new_tab: true

heading_anchors: true
