title: SYNTAX
theme: just-the-docs

plugins:
  - jekyll-toc

url: https://littleweirdo410.github.io/syntax_handbook

aux_links:
  "GitHub":
    - "//github.com/littleweirdo410/syntax_handbook"

aux_links_new_tab: true

heading_anchors: true

nav_enabled: true

kramdown:
  toc_levels: 1..6

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
